### ISSUE TITLE
Can not include i18n files when using model

### ISSUE THREAD

**Issue by XiangShotray** [cap-js-community/odata-v2-adapter#48]
Hi team,
I want to use odatav2proxy to read a folder of srv files to achieve i18n function, but when I enter a path of folder, it reports error as follow:

```
May 15, 2024 05:03:00 PM Logger.js [lw7lgdk0] ERROR: Couldn't find a CDS model for 'undefined' in /Users/*/Documents/GitHub/*/approuter
Error: Couldn't find a CDS model for 'undefined' in /Users/*/Documents/GitHub/*/approuter
    at cds.load (/Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds/lib/compile/load.js:11:36)
    at /Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds-odata-v2-adapter-proxy/lib/index.js:683:26
    at prepareMetadata (/Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds-odata-v2-adapter-proxy/lib/index.js:696:24)
    at getDefaultMetadata (/Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds-odata-v2-adapter-proxy/lib/index.js:676:18)
    at getMetadata (/Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds-odata-v2-adapter-proxy/lib/index.js:606:24)
    at /Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds-odata-v2-adapter-proxy/lib/index.js:285:33
    at /Users/*/Documents/GitHub/*/approuter/node_modules/@sap/cds-odata-v2-adapter-proxy/lib/index.js:293:11
    at Layer.handle [as handle_request] (/Users/*/Documents/GitHub/*/approuter/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/*/Documents/GitHub/*/approuter/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Users/*/Documents/GitHub/*/approuter/node_modules/express/lib/router/route.js:119:3)
#2.0#2024 05 15 17:03:05:482#+08:00#INFO#/requestHandler#####6958e405-0e94-441e-ab15-15567b34fd59####Kq1KTdf6_WQ3u867TDGp2DbMznHzVwMg######lw7lghs7#PLAIN##Missing internal url for request url /sap/opu/odata/sap/ESH_SEARCH_SRV/ServerInfos?$expand=Services/Capabilities#

```

The script to generate srv.json with i18n is like:
```
"cds build --clean && cds compile srv -s all -l all -o ./approuter/srv"
```

The code used as following and it's written in */approuter/index.js:
```
const approuter = require("@sap/approuter");
const router = approuter();

    router.beforeRequestHandler
    .use(pathV2, expressInit)
    .use(odatav2proxy({
        path: '',
        target: '',
        model: `${__dirname}/srv`,
        services: {
            ""
        },
    }));
```

And here is versions of modules used:
```
  "dependencies": {
    "@sap/approuter": "latest",
    "@sap/cds": "^7.2.0",
    "@sap/cds-mtxs": "^1.9.1",
    "@sap/cds-odata-v2-adapter-proxy": "1.8.16"
  },
```

According to the [document](https://www.npmjs.com/package/@sap/cds-odata-v2-adapter-proxy?activeTab=readme), the default value of model is 'all', so I think there must be a way to add more than one srv files into model. I have tried some ways but it doesn't work. Maybe you experts can give me some suggestions about this, thank you!

**Comment by oklemenz2** [comment]
Thanks for reporting your questions. In general I have the following remarks:

- `@sap/cds-odata-v2-adapter-proxy` is deprecated and not maintained since over an year. Please use the replacement `@cap-js-community/odata-v2-adapter`.
- I also would recommend to always use the latest CDS release, currently CDS 7.9
- Is there as specific reason, why you want to have the CDS OData V2 adapter in approuter module? Normally approuter and CDS backend are two different apps, and the CDS OData V2 adapter belongs more to the CDS backend.
- Then the CDS OData V2 adapter would auto-detect the CSN including all i18n bundles, without configuration running as CDS plugin
- Your path, target and services configuration does not look correct. This would basically do nothing and CDS OData V2 adapter would not work correctly.
- Of course you can specific a model, and you can compile a single CSN including all services and all entities via the command ` cds srv -s all -o .` (no cdd build necessary before). To get localization working, you need to make sure, that the i18n files reside next to the generated csn (`srv.json`) in an `i18n` sub-folder. Similar how it is done when calling `cds build --production` in `gen/srv` folder
- The model does not point to a folder, but to the generated CSN `srv.json` or `csn.json`. CDS load will then lookup the i18n files residing relatively next to the CSN in `i18n` or `_i18n` folders
- Details you can find here: https://github.com/cap-js-community/odata-v2-adapter?tab=readme-ov-file#additional-considerations

In general my recommendation would be to try the default CDS plugin path (https://github.com/cap-js-community/odata-v2-adapter?tab=readme-ov-file#getting-started), because everything is set up already, what you are trying to do manually now...
