### ISSUE TITLE
High Severity Mend Vulnerability

### ISSUE THREAD

**Issue by krishraheja-sap** [cap-js-community/odata-v2-adapter#62]
Hi Colleague,

There is a High severity mend vulnerability for micromatch library in @cap-js-community/odata-v2-adapter 1.13.1. Please refer to below screenshot for your reference.

<img width="1618" alt="image" src="https://github.com/user-attachments/assets/1f65acbe-a74c-4189-bc0a-94c7d30e6ef0">

<img width="412" alt="image" src="https://github.com/user-attachments/assets/215daf84-56cf-4fd7-a191-31e0535120dc">

Please do the needful and provide a fix for the same.

Best Regards
Krishan

**Comment by oklemenz2** [comment]
- Fixed with https://github.com/micromatch/micromatch/releases/tag/4.0.8
- Currently no more current release of `http-proxy-middleware` with min dependency of 4.0.8
- But: `http-proxy-middleware` has an open dependency, so an npm update for customer project will update to 4.0.8
- So consumer can fix this issue automatically, by updating his package-lock
- I will update all dependencies, once available...
- Is considered in addition as low-priority issue by micro match
- So no further action here
- Close
