### ISSUE TITLE
Adapter service does not work after change dependency from @sap/cds-odata-v2-adapter-proxy to @cap-js-community/odata-v2-adapter

### ISSUE THREAD

**Issue by SharonChi123** [cap-js-community/odata-v2-adapter#96]
Hi colleagues,

Description:
We have a cap java based Fiori V2 application, where uses OData V2 adapter service to convert request/response from/to ui between OData V2 and OData V4.  We were using @sap/cds-odata-v2-adapter-proxy and worked well. Recently, we change to @cap-js-community/odata-v2-adapter, but the adapter service cannot be reached and get 404 when test locally. 

Here is the repo: https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op
The working version is on master branch.
The changes made on [update/dependency_adapter](https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/tree/update/dependency_adapter).

Details introduction:

1.There is OData V4 Service, the endpoint is set to /api for OData V4 and can be found at here: https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/blob/update/dependency_adapter/srv/src/main/resources/application.properties#L40.
The OData service model is at here: https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/blob/update/dependency_adapter/srv/op-service.cds#L4.

The service runs at http://localhost:8086 on local.

2. There is also a OData V2 adapter service(https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/tree/update/dependency_adapter/adapter), used to convert between OData V2 and V4. And service will start locally by running PORT=5000 node local-index.js under adapter folder and listen on port 5000. If look into the file local-index.js(https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/blob/update/dependency_adapter/adapter/local-index.js#L15)

app.use(proxy({
    build: false,
    path: "odata-v2",
    target: targetPath, => http://localhost:8086
    targetPath: '',  
    model: "./csn.json",    
    services: {
      "/api/OPService": "OPService"
    }
  }));

Here "build":false and "model":"/.csn.json" . Because csn.json and i18n files will be copied into adapter folder after run 'mvn clean package'.

3. dataSources  "uri": "/op_service/odata-v2/api/OPService/" in manifest.json file

Reproduce:
1. start OData V4 service locally(https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/tree/update/dependency_adapter#running-the-odata-v4-server). Running at http://localhost:8086.
2. start OData V2 Adapter service locally.(https://github.wdf.sap.corp/ISUtilitiesIoT/c4e-eds-op/tree/update/dependency_adapter#running-the-odata-v2-adapter) Running at http://localhost:5000.
3. send Get request to Adapter service http://localhost:5000/odata-v2/api/OPService/$metadata and get 404. Expecting to redirect to http://localhost:8086/api/OPService. 

Need a help on this, thank you in advance!

**Comment by oklemenz2** [comment]
Thanks for reporting this issue. I will have a look.

**Comment by oklemenz2** [comment]
Currently the usage of CDS OData V2 Adapter in combination with CAP Java is not in focus anymore, as CAP Java provides an OData V2 protocol out-of-the-box. Details: https://cap.cloud.sap/docs/java/migration#v2adapter
Maybe you want to evaluate the migration to that, then you can get rid of the proxy component completely. 

But nevertheless, a change broke the usage with CAP Java. With the latest release  **1.13.8**, I provided an option to get it back working, so that you can also continue with @cap-js-community/odata-v2-adapter.

https://registry.npmjs.org/@cap-js-community/odata-v2-adapter/-/odata-v2-adapter-1.13.8.tgz

You just need to add the following line to your proxy options:

```
registerOnListening: false
```

As you do not start the CDS adapter via CDS `server.js` the CDS `listening` event does not come. Setting the option, the routes are registered directly, without waiting for the event. 

Please check, if that works for you.

**Comment by SharonChi123** [comment]
Hi Oliver,

Thank you for the help. We need to Adapter for some ui functionalities even though the CAP Java OData V2 is out of the box. I tried your suggestion above. Unfortunately, it still does not work.

**Comment by oklemenz2** [comment]
Solved with 1.13.8.
